# Generated by Django 5.2 on 2025-05-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_studygroup_groupmessage_studygroupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used_by',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItem',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
