# Generated by Django 5.2 on 2025-06-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_assignmentsubmission_is_graded_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=set(),
        ),
    ]
